
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "JobFunctions" (
    "Code" character varying(20) NOT NULL,
    "Name" character varying(50) NOT NULL,
    "HierarchyLevel" smallint NOT NULL,
    CONSTRAINT "PK_JobFunctions" PRIMARY KEY ("Code")
);

CREATE TABLE "Employees" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "DocNumber" character varying(20) NOT NULL,
    "BirthDate" text NOT NULL,
    "JobFunctionCode" character varying(20) NOT NULL,
    "ManagerID" integer,
    "CreationDate" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletionDate" timestamp with time zone,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Employees_Employees_ManagerID" FOREIGN KEY ("ManagerID") REFERENCES "Employees" ("ID"),
    CONSTRAINT "FK_Employees_JobFunctions_JobFunctionCode" FOREIGN KEY ("JobFunctionCode") REFERENCES "JobFunctions" ("Code") ON DELETE CASCADE
);

CREATE TABLE "Phones" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Label" character varying(100) NOT NULL,
    "Number" character varying(30) NOT NULL,
    "EmployeeID" integer NOT NULL,
    CONSTRAINT "PK_Phones" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Phones_Employees_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES "Employees" ("ID") ON DELETE CASCADE
);

INSERT INTO "JobFunctions" ("Code", "HierarchyLevel", "Name")
VALUES ('0001', 1000, 'RH Manager');
INSERT INTO "JobFunctions" ("Code", "HierarchyLevel", "Name")
VALUES ('0002', 500, 'RH Analyst');
INSERT INTO "JobFunctions" ("Code", "HierarchyLevel", "Name")
VALUES ('0003', 500, 'Tech Leader');
INSERT INTO "JobFunctions" ("Code", "HierarchyLevel", "Name")
VALUES ('0004', 100, 'IT Analyst');
INSERT INTO "JobFunctions" ("Code", "HierarchyLevel", "Name")
VALUES ('0005', 1, 'Intern');

INSERT INTO "Employees" ("ID", "BirthDate", "CreationDate", "DeletionDate", "DocNumber", "Email", "FirstName", "IsDeleted", "JobFunctionCode", "LastName", "ManagerID", "PasswordHash")
VALUES (-1, '1990-01-01', TIMESTAMPTZ '2025-03-17T14:35:00Z', NULL, '0001', 'admin.rh@faces.com', 'RH', FALSE, '0001', 'Admin', NULL, 'i+rcXhRFTdUTkNVTJ07ydQ==.HXcBql16eQsd/uam7bZdKvPhAIAotA8kbwx7FBsrRBc=');

CREATE UNIQUE INDEX "IX_Employees_DocNumber" ON "Employees" ("DocNumber");

CREATE INDEX "IX_Employees_JobFunctionCode" ON "Employees" ("JobFunctionCode");

CREATE INDEX "IX_Employees_ManagerID" ON "Employees" ("ManagerID");

CREATE INDEX "IX_Phones_EmployeeID" ON "Phones" ("EmployeeID");

SELECT setval(
    pg_get_serial_sequence('"Employees"', 'ID'),
    GREATEST(
        (SELECT MAX("ID") FROM "Employees") + 1,
        nextval(pg_get_serial_sequence('"Employees"', 'ID'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250317143503_init', '9.0.3');

COMMIT;

